### ISSUE TITLE
Maybe a bug when paring config file?

### ISSUE THREAD

**Issue by StarDuster** [phoenixlzx/MinoriWiki#3]
For example, in config.yml

```
# Custom
custom:
  time: YYYY-MM-DD HH:mm:ss
  disqus:
  markdown:
    gfm: true
    pedantic: false
    sanitize: false
    tables: true
    breaks: true
    smartLists: true
    smartypants: true
  editor:subl    #I missed a blank after ':' 
```

it comes a error when `minori note`:

```
/usr/local/lib/node_modules/minori/lib/note.js:42
    var file = path.resolve(cwd + '/' + config['dir'].source + '/' + filename + '.md');
                                                     ^

TypeError: Cannot read property 'source' of undefined
    at module.exports (/usr/local/lib/node_modules/minori/lib/note.js:42:54)
    at /usr/local/lib/node_modules/minori/lib/index.js:28:21
    at /usr/local/lib/node_modules/minori/lib/index.js:76:13
    at FSReqWrap.oncomplete (fs.js:82:15)
```

The error messages are the same no matter where the missing blank is.

I'm not sure whether you have already known about this problem?
